In [1]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import gmaps.datasets
import os

# Import API key
from config import weather_api_key
from citipy import citipy

# Output File (CSV)
output_data_file = "gmaps/coord_cnty.csv"
city_map = pd.read_csv(output_data_file)

# Range of latitudes and longitudes, changed for US
lat_range = (-38, 38)
lng_range = (-97, 97)

In [2]:
# List for holding lat_lngs and cities
lat_lngs = []
cities = ['Los Angeles', 'Riverside', 'Victorville','Bakersfield','Cartago','Thousand Oaks','Irvine','Escondido',
          'Brawley','Houston','Conroe','Dayton','Beach City','League City','Angleton','Rosenberg','Hempstead',
          'Dallas','Fort Worth','Weatherford','Decatur','Denton','McKinney','Cleburne','Palmer','Terrell','Rockwall',
          'Miami','Davie','West Palm Beach','Key West','Golden Gate','Fort Myers','Clewiston','Buckhead Ridge',
          'Taylor Creek','Palm City']

# Create a set of random lat and lng combinations
lats = np.random.uniform(lat_range[0], lat_range[1], size=40)
lngs = np.random.uniform(lng_range[0], lng_range[1], size=40)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name

# Print the city count to confirm sufficient count
len(cities)

37

In [3]:
# cities

In [4]:
#Working with a loop
url = "http://api.openweathermap.org/data/2.5/weather?"

#Set up lists to hold response info
lat1 = []
lng1 = []
counter = 0
sets = 1

# Loop through the list of cities set by previous loop and perform a request for data on each []
print("-------Beginning of Data Retrieval--------")

for city in cities:
    city=city
    
    query_url = url + "&q=" + city + "&appid=" + weather_api_key + "&units=Imperial"
    response = requests.get(query_url).json()
    
    try:
        print(f"Processing Record {counter} of Set {sets} | {city}")
        lat1.append(response['coord']['lat'])
        lng1.append(response['coord']['lon'])

    except: 
        print('City not found. Skipping...')
        lat1.append(np.nan)
        lng1.append(np.nan)
        
    counter = counter + 1
    if counter == 50:
        counter = 0
        sets = sets + 1

print("-----------------------")      
print("Data Retrieval Complete")
print("-----------------------")

-------Beginning of Data Retrieval--------
Processing Record 0 of Set 1 | Los Angeles
Processing Record 1 of Set 1 | Riverside
Processing Record 2 of Set 1 | Victorville
Processing Record 3 of Set 1 | Bakersfield
Processing Record 4 of Set 1 | Cartago
Processing Record 5 of Set 1 | Thousand Oaks
Processing Record 6 of Set 1 | Irvine
Processing Record 7 of Set 1 | Escondido
Processing Record 8 of Set 1 | Brawley
Processing Record 9 of Set 1 | Houston
Processing Record 10 of Set 1 | Conroe
Processing Record 11 of Set 1 | Dayton
Processing Record 12 of Set 1 | Beach City
Processing Record 13 of Set 1 | League City
Processing Record 14 of Set 1 | Angleton
Processing Record 15 of Set 1 | Rosenberg
Processing Record 16 of Set 1 | Hempstead
Processing Record 17 of Set 1 | Dallas
Processing Record 18 of Set 1 | Fort Worth
Processing Record 19 of Set 1 | Weatherford
Processing Record 20 of Set 1 | Decatur
Processing Record 21 of Set 1 | Denton
Processing Record 22 of Set 1 | McKinney
Processing Record 23 of Set 1 | Cleburne
Processing Record 24 of Set 1 | Palmer
Processing Record 25 of Set 1 | Terrell
Processing Record 26 of Set 1 | Rockwall
Processing Record 27 of Set 1 | Miami
Processing Record 28 of Set 1 | Davie
Processing Record 29 of Set 1 | West Palm Beach
Processing Record 30 of Set 1 | Key West
Processing Record 31 of Set 1 | Golden Gate
Processing Record 32 of Set 1 | Fort Myers
Processing Record 33 of Set 1 | Clewiston
Processing Record 34 of Set 1 | Buckhead Ridge
Processing Record 35 of Set 1 | Taylor Creek
Processing Record 36 of Set 1 | Palm City
-----------------------
Data Retrieval Complete
-----------------------

In [5]:
#Create  a data frame from all lists

map_dict = {
    "City": cities,
    "Lat": lat1,
    "Lng": lng1,
}

map_data = pd.DataFrame(map_dict)
# map_data

In [6]:
#Export the city data into a .csv.
map_data.to_csv('output_data/county_coord_data.csv', index=False)

In [17]:
# Output File (CSV)
output_file = "data/capitol_api.csv"
cap_map = pd.read_csv(output_file)

# Range of latitudes and longitudes, changed for US
lat_range = (-90, 90)
lng_range = (-180, 180)

In [18]:
# cap_map

In [20]:
# List for holding lat_lngs and cities
lat_lngs = []
cap_cities = ['Montgomery','Phoenix','Little Rock','Sacramento','Denver','Helena','Lincoln','Carson City','Concord',
              'Trenton','Santa Fe','Hartford','Albany','Dover','Raleigh','Tallahassee','Bismarck','Atlanta','Columbus',
              'Oklahoma City','Boise','Salem','Springfield','Harrisburg','Indianapolis','Providence','Des Moines',
              'Columbia','Topeka','Pierre','Frankfort','Nashville','Baton Rouge','Austin','Augusta','Salt Lake City',
              'Annapolis','Montpelier','Boston','Richmond','Lansing','Olympia','St. Paul','Charleston','Jackson','Madison',
              'Jefferson City','Cheyenne']

# Create a set of random lat and lng combinations
lats = np.random.uniform(lat_range[0], lat_range[1], size=50)
lngs = np.random.uniform(lng_range[0], lng_range[1], size=50)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name

# Print the city count to confirm sufficient count
len(cap_cities)

48

In [22]:
#Working with a loop
url = "http://api.openweathermap.org/data/2.5/weather?"

#Set up lists to hold response info
lat2 = []
lng2 = []
counter = 0
sets = 1

# Loop through the list of cities set by previous loop and perform a request for data on each []
print("-------Beginning of Data Retrieval--------")

for city in cap_cities:
    city=city
    
    query_url = url + "&q=" + city + "&appid=" + weather_api_key + "&units=Imperial"
    response = requests.get(query_url).json()
    
    try:
        print(f"Processing Record {counter} of Set {sets} | {city}")
        lat2.append(response['coord']['lat'])
        lng2.append(response['coord']['lon'])

    except: 
        print('City not found. Skipping...')
        lat2.append(np.nan)
        lng2.append(np.nan)
        
    counter = counter + 1
    if counter == 50:
        counter = 0
        sets = sets + 1

print("-----------------------")      
print("Data Retrieval Complete")
print("-----------------------")

-------Beginning of Data Retrieval--------
Processing Record 0 of Set 1 | Montgomery
Processing Record 1 of Set 1 | Phoenix
Processing Record 2 of Set 1 | Little Rock
Processing Record 3 of Set 1 | Sacramento
Processing Record 4 of Set 1 | Denver
Processing Record 5 of Set 1 | Helena
Processing Record 6 of Set 1 | Lincoln
Processing Record 7 of Set 1 | Carson City
Processing Record 8 of Set 1 | Concord
Processing Record 9 of Set 1 | Trenton
Processing Record 10 of Set 1 | Santa Fe
Processing Record 11 of Set 1 | Hartford
Processing Record 12 of Set 1 | Albany
Processing Record 13 of Set 1 | Dover
Processing Record 14 of Set 1 | Raleigh
Processing Record 15 of Set 1 | Tallahassee
Processing Record 16 of Set 1 | Bismarck
Processing Record 17 of Set 1 | Atlanta
Processing Record 18 of Set 1 | Columbus
Processing Record 19 of Set 1 | Oklahoma City
Processing Record 20 of Set 1 | Boise
Processing Record 21 of Set 1 | Salem
Processing Record 22 of Set 1 | Springfield
Processing Record 23 of Set 1 | Harrisburg
Processing Record 24 of Set 1 | Indianapolis
Processing Record 25 of Set 1 | Providence
Processing Record 26 of Set 1 | Des Moines
Processing Record 27 of Set 1 | Columbia
Processing Record 28 of Set 1 | Topeka
Processing Record 29 of Set 1 | Pierre
Processing Record 30 of Set 1 | Frankfort
Processing Record 31 of Set 1 | Nashville
Processing Record 32 of Set 1 | Baton Rouge
Processing Record 33 of Set 1 | Austin
Processing Record 34 of Set 1 | Augusta
Processing Record 35 of Set 1 | Salt Lake City
Processing Record 36 of Set 1 | Annapolis
Processing Record 37 of Set 1 | Montpelier
Processing Record 38 of Set 1 | Boston
Processing Record 39 of Set 1 | Richmond
Processing Record 40 of Set 1 | Lansing
Processing Record 41 of Set 1 | Olympia
Processing Record 42 of Set 1 | St. Paul
Processing Record 43 of Set 1 | Charleston
Processing Record 44 of Set 1 | Jackson
Processing Record 45 of Set 1 | Madison
Processing Record 46 of Set 1 | Jefferson City
Processing Record 47 of Set 1 | Cheyenne
-----------------------
Data Retrieval Complete
-----------------------

In [26]:
#Create  a data frame from all lists

cap_dict = {
    "City": cap_cities,
    "Lat": lat2,
    "Lng": lng2,
}

cap_data = pd.DataFrame(cap_dict)
cap_data

              City      Lat       Lng
0       Montgomery  39.1501  -77.1997
1          Phoenix  33.4484 -112.0740
2      Little Rock  34.7465  -92.2896
3       Sacramento  38.4666 -121.3177
4           Denver  39.7392 -104.9847
5           Helena  46.5927 -112.0361
6          Lincoln  40.8000  -96.6670
7      Carson City  39.1638 -119.7674
8          Concord  37.9780 -122.0311
9          Trenton  40.2170  -74.7429
10        Santa Fe -31.6333  -60.7000
11        Hartford  41.7668  -72.7662
12          Albany  42.6001  -73.9662
13           Dover  39.1582  -75.5244
14         Raleigh  35.7721  -78.6386
15     Tallahassee  30.4383  -84.2807
16        Bismarck  46.8083 -100.7837
17         Atlanta  33.7490  -84.3880
18        Columbus  39.9612  -82.9988
19   Oklahoma City  35.4676  -97.5164
20           Boise  43.6135 -116.2035
21           Salem  11.6500   78.1667
22     Springfield  37.2153  -93.2982
23      Harrisburg  40.2737  -76.8844
24    Indianapolis  39.7684  -86.1580
25      Providence  41.8240  -71.4128
26      Des Moines  41.6005  -93.6091
27        Columbia  34.0007  -81.0348
28          Topeka  39.0483  -95.6780
29          Pierre  44.3683 -100.3510
30       Frankfort -27.2667   28.4833
31       Nashville  36.1659  -86.7844
32     Baton Rouge  30.4508  -91.1545
33          Austin  30.2672  -97.7431
34         Augusta  48.3667   10.8833
35  Salt Lake City  40.7608 -111.8911
36       Annapolis  38.9785  -76.4922
37      Montpelier  44.2601  -72.5754
38          Boston  42.3584  -71.0598
39        Richmond  37.5538  -77.4603
40         Lansing  42.7325  -84.5555
41         Olympia  47.0379 -122.9007
42        St. Paul  44.9444  -93.0933
43      Charleston  32.7766  -79.9309
44         Jackson  42.4165 -122.8345
45         Madison  34.7334  -86.5667
46  Jefferson City  38.5767  -92.1735
47        Cheyenne  41.1400 -104.8203

In [27]:
#Export the city data into a .csv.
cap_data.to_csv('output_data/state_cap_data.csv', index=False)